import type { Metadata } from 'next'
import { Geist_Mono, Fira_Code, Inter } from 'next/font/google'
import { LayoutRoot } from '@/components/LayoutRoot'

import '././../styles/reset.scss'

import styles from './layout.module.scss'
import { Header } from '@/components/Header/Header'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const firaCode = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={styles.container}>
      <body
        className={`${geistMono.variable} ${firaCode.variable} ${inter.variable}`}
      >
        <LayoutRoot>
          <Header />
          {children}
        </LayoutRoot>
      </body>
    </html>
  )
}
